import './globals.css'
import 'flowbite/dist/flowbite.css';
import { Inter } from 'next/font/google'
import Nav from './Components/Menu/Nav';
import Footer from './Components/Footer/Footer';
import Social from './Components/Social/Social';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Confederación de Trabajadores de México',
  description: 'Generated by create next app',
}

export default function RootLayout({ children, displayNavFooter = true }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
      </body>
    </html>
  )
}
